from app.models import Product, Segment


PRODUCTS = [
    Product(
        id=101,
        name="Yun Karisimli Palto",
        gender="Women",
        master_category="Apparel",
        sub_category="Outerwear",
        article_type="Coats",
        base_colour="Navy",
        usage="Smart Casual",
        price=3899,
        sale_price=2499,
        image_url="https://images.unsplash.com/photo-1548624313-0396c75e4b1a?auto=format&fit=crop&w=900&q=80",
        product_url="#",
    ),
    Product(
        id=102,
        name="Slim Fit Pantolon",
        gender="Women",
        master_category="Apparel",
        sub_category="Bottomwear",
        article_type="Trousers",
        base_colour="Black",
        usage="Smart Casual",
        price=1299,
        sale_price=899,
        image_url="https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&q=80",
        product_url="#",
    ),
    Product(
        id=103,
        name="Kasmir Kazak",
        gender="Women",
        master_category="Apparel",
        sub_category="Topwear",
        article_type="Sweaters",
        base_colour="Beige",
        usage="Casual",
        price=1900,
        sale_price=1200,
        image_url="https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80",
        product_url="#",
    ),
    Product(
        id=104,
        name="Deri Loafer",
        gender="Women",
        master_category="Footwear",
        sub_category="Shoes",
        article_type="Loafers",
        base_colour="Black",
        usage="Smart Casual",
        price=1799,
        sale_price=1199,
        image_url="https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=80",
        product_url="#",
    ),
    Product(
        id=201,
        name="Lacivert Blazer",
        gender="Men",
        master_category="Apparel",
        sub_category="Outerwear",
        article_type="Blazers",
        base_colour="Navy",
        usage="Formal",
        price=3299,
        sale_price=2199,
        image_url="https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80",
        product_url="#",
    ),
    Product(
        id=202,
        name="Oxford Gomlek",
        gender="Men",
        master_category="Apparel",
        sub_category="Topwear",
        article_type="Shirts",
        base_colour="White",
        usage="Formal",
        price=1199,
        sale_price=749,
        image_url="https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=900&q=80",
        product_url="#",
    ),
    Product(
        id=203,
        name="Koyu Denim Pantolon",
        gender="Men",
        master_category="Apparel",
        sub_category="Bottomwear",
        article_type="Jeans",
        base_colour="Blue",
        usage="Casual",
        price=1499,
        sale_price=899,
        image_url="https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=80",
        product_url="#",
    ),
    Product(
        id=204,
        name="Minimal Sneaker",
        gender="Men",
        master_category="Footwear",
        sub_category="Shoes",
        article_type="Sneakers",
        base_colour="White",
        usage="Casual",
        price=1999,
        sale_price=1299,
        image_url="https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=80",
        product_url="#",
    ),
    Product(
        id=301,
        name="Renkli Sweatshirt",
        gender="Boys",
        master_category="Apparel",
        sub_category="Topwear",
        article_type="Sweatshirts",
        base_colour="Purple",
        usage="Casual",
        price=799,
        sale_price=499,
        image_url="https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=900&q=80",
        product_url="#",
    ),
    Product(
        id=302,
        name="Esnek Jogger",
        gender="Boys",
        master_category="Apparel",
        sub_category="Bottomwear",
        article_type="Joggers",
        base_colour="Grey",
        usage="Sports",
        price=699,
        sale_price=449,
        image_url="https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?auto=format&fit=crop&w=900&q=80",
        product_url="#",
    ),
    Product(
        id=303,
        name="Parlak Mont",
        gender="Girls",
        master_category="Apparel",
        sub_category="Outerwear",
        article_type="Jackets",
        base_colour="Lilac",
        usage="Casual",
        price=1099,
        sale_price=699,
        image_url="https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80",
        product_url="#",
    ),
    Product(
        id=304,
        name="Rahat Sneaker",
        gender="Girls",
        master_category="Footwear",
        sub_category="Shoes",
        article_type="Sneakers",
        base_colour="Pink",
        usage="Sports",
        price=899,
        sale_price=549,
        image_url="https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=900&q=80",
        product_url="#",
    ),
]


def get_catalog() -> list[Product]:
    return PRODUCTS


def get_segment_genders(segment: Segment) -> set[str]:
    if segment == "child":
        return {"Boys", "Girls"}

    return {"Men", "Women"}


def filter_products_by_segment(segment: Segment) -> list[Product]:
    genders = get_segment_genders(segment)
    return [product for product in PRODUCTS if product.gender in genders]
